# Generated by Django 4.2 on 2023-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
