# Generated by Django 4.2 on 2023-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
